CREATE TABLE `competitor_audits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`auditId` int NOT NULL,
	`jobId` int NOT NULL,
	`userId` int NOT NULL,
	`url` text NOT NULL,
	`domain` varchar(255) NOT NULL,
	`pageTitle` text,
	`citationCount` int NOT NULL DEFAULT 0,
	`rank` int NOT NULL DEFAULT 1,
	`status` enum('pending','running','completed','failed') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`overallScore` int,
	`technicalScore` int,
	`structuredDataScore` int,
	`contentStructureScore` int,
	`eeatScore` int,
	`aiCrawlersScore` int,
	`metaTagsScore` int,
	`brandAuthorityScore` int,
	`tech_https` int,
	`tech_noindex` int,
	`tech_nosnippet` int,
	`tech_canonical` int,
	`tech_viewport` int,
	`tech_robots_disallow` int,
	`tech_response_time_ms` int,
	`tech_page_size_kb` int,
	`tech_sitemap` int,
	`tech_hreflang` int,
	`tech_max_snippet` int,
	`tech_noai_directive` int,
	`sd_jsonld_present` int,
	`sd_high_value_schema` int,
	`sd_faq_schema` int,
	`sd_howto_schema` int,
	`sd_article_product` int,
	`sd_organization` int,
	`sd_schema_completeness` int,
	`sd_author_schema` int,
	`sd_date_signals` int,
	`sd_breadcrumb` int,
	`cs_h1_present` int,
	`cs_heading_hierarchy` int,
	`cs_passage_optimization` int,
	`cs_tldr_summary` int,
	`cs_faq_section` int,
	`cs_semantic_chunking` int,
	`cs_entity_richness` int,
	`cs_readability` int,
	`cs_semantic_triples` int,
	`cs_lists_present` int,
	`cs_content_length` int,
	`cs_information_gain` int,
	`cs_answer_patterns` int,
	`cs_external_citations` int,
	`cs_data_points` int,
	`eeat_author_byline` int,
	`eeat_about_page` int,
	`eeat_contact_info` int,
	`eeat_legal_pages` int,
	`eeat_review_signals` int,
	`eeat_trust_signals` int,
	`eeat_publication_date` int,
	`eeat_experience_signals` int,
	`eeat_expertise_signals` int,
	`ai_url_access` int,
	`ai_full_block` int,
	`ai_training_bots` int,
	`ai_sitemap_crawlers` int,
	`ai_llms_txt` int,
	`mt_title_tag` int,
	`mt_meta_description` int,
	`mt_og_title` int,
	`mt_og_description` int,
	`mt_og_image` int,
	`mt_twitter_card` int,
	`mt_lang_attribute` int,
	`ba_brand_consistency` int,
	`ba_knowledge_panel` int,
	`ba_media_presence` int,
	`ba_industry_credentials` int,
	`ba_social_proof` int,
	`ba_niche_authority` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `competitor_audits_id` PRIMARY KEY(`id`)
);
