/**
 * narrativeGenerator.ts
 *
 * Generates a one-paragraph, actionable diagnosis connecting:
 *  - Citation Intelligence results (which engines cited the page, how many queries)
 *  - Top 3 gaps from Gap Analysis (what competitors have that the target lacks)
 *
 * Output is a structured JSON object so the frontend can render it with rich UI.
 * Designed to be the "aha moment" that converts data into a decision.
 *
 * Architecture:
 *  - Called lazily (on-demand) from the tRPC procedure, NOT during the citation job
 *  - Result is cached in-memory per auditId for 10 minutes (cheap, avoids re-runs)
 *  - Falls back to a deterministic template if LLM is unavailable
 */

import { invokeLLM } from "../_core/llm";
import type { GapItem } from "../competitor/gapAnalysis";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface CitationNarrativeInput {
  auditId: number;
  url: string;
  /** Number of AI engines that cited the page (0–4) */
  citedEngineCount: number;
  /** Total engines checked */
  totalEngines: number;
  /** Which engines cited (e.g. ["google", "perplexity"]) */
  citingEngines: string[];
  /** Which engines did NOT cite */
  missingEngines: string[];
  /** Total citation checks performed */
  totalChecks: number;
  /** Top 3 gaps from gap analysis (highest priority first) */
  topGaps: Pick<GapItem, "label" | "category" | "categoryLabel" | "impact" | "recommendation" | "competitorPassCount" | "competitorTotal" | "targetValue">[];
  /** Page language (pl/en) */
  language?: string;
}

export interface CitationNarrativeResult {
  /** One-sentence verdict */
  verdict: string;
  /** 2–3 sentence diagnosis connecting citation results to top gaps */
  diagnosis: string;
  /** The single most important action to take */
  primaryAction: string;
  /** Which gap is the root cause (label) */
  rootCauseGap: string | null;
  /** Confidence: high / medium / low */
  confidence: "high" | "medium" | "low";
  /** Whether this was generated by LLM or is a deterministic fallback */
  source: "llm" | "template";
}

// ─── In-memory cache ──────────────────────────────────────────────────────────

const CACHE_TTL_MS = 10 * 60 * 1000; // 10 minutes
const cache = new Map<number, { result: CitationNarrativeResult; expiresAt: number }>();

function getCached(auditId: number): CitationNarrativeResult | null {
  const entry = cache.get(auditId);
  if (!entry) return null;
  if (Date.now() > entry.expiresAt) {
    cache.delete(auditId);
    return null;
  }
  return entry.result;
}

function setCache(auditId: number, result: CitationNarrativeResult): void {
  cache.set(auditId, { result, expiresAt: Date.now() + CACHE_TTL_MS });
}

/** Exported for test isolation only — clears all cached narratives */
export function clearNarrativeCache(): void {
  cache.clear();
}

// ─── Deterministic fallback ───────────────────────────────────────────────────

function buildTemplateFallback(input: CitationNarrativeInput): CitationNarrativeResult {
  const isPl = (input.language ?? "pl") === "pl";
  const isVisible = input.citedEngineCount > 0;
  const topGap = input.topGaps[0] ?? null;

  const engineLabels: Record<string, string> = {
    google: "Google AI Overviews",
    perplexity: "Perplexity",
    gemini: "Gemini",
    chatgpt: "ChatGPT",
  };

  const missingNames = input.missingEngines.map(e => engineLabels[e] ?? e);
  const citingNames = input.citingEngines.map(e => engineLabels[e] ?? e);

  if (!isVisible) {
    const gapText = topGap
      ? (isPl
          ? `Najczęstszą przyczyną braku cytowań jest ${topGap.label.toLowerCase()} — ${topGap.competitorPassCount}/${topGap.competitorTotal} Twoich rywali to spełnia.`
          : `The most common reason for missing citations is ${topGap.label} — ${topGap.competitorPassCount}/${topGap.competitorTotal} of your competitors meet this requirement.`)
      : (isPl ? "Brak danych o lukach w stosunku do konkurencji." : "No gap data available.");

    return {
      verdict: isPl
        ? `Twoja strona nie jest cytowana przez żaden z ${input.totalEngines} sprawdzonych silników AI.`
        : `Your page is not cited by any of the ${input.totalEngines} AI engines checked.`,
      diagnosis: isPl
        ? `Sprawdziliśmy ${input.totalChecks} zapytań w ${input.totalEngines} silnikach AI (${missingNames.join(", ")}). Twoja domena nie pojawiła się w żadnej odpowiedzi. ${gapText}`
        : `We checked ${input.totalChecks} queries across ${input.totalEngines} AI engines (${missingNames.join(", ")}). Your domain did not appear in any response. ${gapText}`,
      primaryAction: topGap
        ? (isPl ? topGap.recommendation : topGap.recommendation)
        : (isPl ? "Dodaj FAQ schema i popraw strukturę treści." : "Add FAQ schema and improve content structure."),
      rootCauseGap: topGap?.label ?? null,
      confidence: "low",
      source: "template",
    };
  }

  return {
    verdict: isPl
      ? `Twoja strona jest cytowana przez ${input.citedEngineCount} z ${input.totalEngines} silników AI.`
      : `Your page is cited by ${input.citedEngineCount} of ${input.totalEngines} AI engines.`,
    diagnosis: isPl
      ? `${citingNames.join(" i ")} ${input.citedEngineCount === 1 ? "cytuje" : "cytują"} Twoją stronę. ${missingNames.length > 0 ? `Brakuje Cię w: ${missingNames.join(", ")}.` : ""} ${topGap ? `Największa luka to ${topGap.label.toLowerCase()} — ${topGap.competitorPassCount}/${topGap.competitorTotal} rywali to ma.` : ""}`
      : `${citingNames.join(" and ")} ${input.citedEngineCount === 1 ? "cites" : "cite"} your page. ${missingNames.length > 0 ? `Missing from: ${missingNames.join(", ")}.` : ""} ${topGap ? `The biggest gap is ${topGap.label} — ${topGap.competitorPassCount}/${topGap.competitorTotal} competitors have it.` : ""}`,
    primaryAction: topGap?.recommendation ?? (isPl ? "Kontynuuj monitorowanie widoczności." : "Continue monitoring visibility."),
    rootCauseGap: topGap?.label ?? null,
    confidence: "low",
    source: "template",
  };
}

// ─── LLM-based generator ──────────────────────────────────────────────────────

const ENGINE_DISPLAY: Record<string, string> = {
  google: "Google AI Overviews",
  perplexity: "Perplexity",
  gemini: "Gemini",
  chatgpt: "ChatGPT",
};

export async function generateCitationNarrative(
  input: CitationNarrativeInput
): Promise<CitationNarrativeResult> {
  // Check cache first
  const cached = getCached(input.auditId);
  if (cached) return cached;

  // If no gaps data, use template
  if (input.topGaps.length === 0) {
    const result = buildTemplateFallback(input);
    setCache(input.auditId, result);
    return result;
  }

  const isPl = (input.language ?? "pl") === "pl";
  const lang = isPl ? "Polish" : "English";

  const citingNames = input.citingEngines.map(e => ENGINE_DISPLAY[e] ?? e);
  const missingNames = input.missingEngines.map(e => ENGINE_DISPLAY[e] ?? e);

  const gapsText = input.topGaps
    .slice(0, 3)
    .map((g, i) => `${i + 1}. ${g.label} (${g.categoryLabel}) — ${g.competitorPassCount}/${g.competitorTotal} competitors pass — ${g.impact}`)
    .join("\n");

  const systemPrompt = `You are a senior GEO (Generative Engine Optimization) analyst. Your job is to write a concise, empathetic, and actionable diagnosis for a website owner who just ran an AI citation check.

RULES:
- Write ONLY in ${lang}
- Be specific — use the actual engine names and gap labels provided
- The "diagnosis" must connect the citation result to the most likely root cause gap
- The "primaryAction" must be a single concrete sentence (not a list)
- The "verdict" must be one sentence, factual, no fluff
- Confidence: "high" if citedEngineCount >= 2 AND topGaps.length >= 2, "medium" if partial data, "low" otherwise
- rootCauseGap: the label of the gap most likely causing the citation problem (or null if page is fully visible)
- DO NOT use jargon like "SEO", "schema markup" without explaining what it means in plain language
- Tone: direct, empathetic, like a trusted advisor — not a robot`;

  const userPrompt = `Citation check results for: ${input.url}

Cited by: ${citingNames.length > 0 ? citingNames.join(", ") : "none"}
Missing from: ${missingNames.length > 0 ? missingNames.join(", ") : "none"}
Total queries checked: ${input.totalChecks}
Total engines: ${input.totalEngines}

Top gaps vs competitors:
${gapsText}

Write a CitationNarrative JSON object.`;

  try {
    const response = await invokeLLM({
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      response_format: {
        type: "json_schema",
        json_schema: {
          name: "citation_narrative",
          strict: true,
          schema: {
            type: "object",
            properties: {
              verdict: { type: "string", description: "One-sentence factual verdict" },
              diagnosis: { type: "string", description: "2-3 sentence diagnosis connecting citation results to root cause gap" },
              primaryAction: { type: "string", description: "Single most important action to take" },
              rootCauseGap: {
                anyOf: [{ type: "string" }, { type: "null" }],
                description: "Label of the gap most likely causing the citation problem, or null",
              },
              confidence: {
                type: "string",
                enum: ["high", "medium", "low"],
                description: "Confidence level of the diagnosis",
              },
            },
            required: ["verdict", "diagnosis", "primaryAction", "rootCauseGap", "confidence"],
            additionalProperties: false,
          },
        },
      },
    });

    const raw = response?.choices?.[0]?.message?.content;
    if (!raw) throw new Error("Empty LLM response");

    const parsed = typeof raw === "string" ? JSON.parse(raw) : raw;

    const result: CitationNarrativeResult = {
      verdict: String(parsed.verdict ?? ""),
      diagnosis: String(parsed.diagnosis ?? ""),
      primaryAction: String(parsed.primaryAction ?? ""),
      rootCauseGap: parsed.rootCauseGap ? String(parsed.rootCauseGap) : null,
      confidence: (["high", "medium", "low"].includes(parsed.confidence) ? parsed.confidence : "medium") as "high" | "medium" | "low",
      source: "llm",
    };

    setCache(input.auditId, result);
    return result;
  } catch (err) {
    console.error("[CitationNarrative] LLM error, falling back to template:", err);
    const result = buildTemplateFallback(input);
    setCache(input.auditId, result);
    return result;
  }
}
